### Bandwidth filter
POST http://localhost:3000/master?min_bitrate=800000&max_bitrate=2000000
Content-Type: text/plain; charset=UTF-8

< ../manifest-filter/manifests/master.m3u8

### Frame rate filter
POST http://localhost:3000/master?rate=60
Content-Type: text/plain; charset=UTF-8

< ../manifest-filter/manifests/master.m3u8

### Mixing two filters (bandwidth and frame rate)
POST http://localhost:3000/master?rate=30&min_bitrate=800000&max_bitrate=2000000
Content-Type: text/plain; charset=UTF-8

< ../manifest-filter/manifests/master.m3u8

### Set first variant by index
POST http://localhost:3000/master?variant_index=1
Content-Type: text/plain; charset=UTF-8

< ../manifest-filter/manifests/master.m3u8

### Set first variant by index
POST http://localhost:3000/master?closest_bandwidth=1500000
Content-Type: text/plain; charset=UTF-8

< ../manifest-filter/manifests/master.m3u8

### Filter DVR
POST http://localhost:3000/media?dvr=15
Content-Type: text/plain; charset=UTF-8

< ../manifest-filter/manifests/media.m3u8
